services:
  - type: web
    name: book-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    runtime: python
    region: oregon
